import { env } from 'process';

export default {
  REDIS_MESSAGE_BROKER: 'REDIS_MESSAGE_BROKER',
  ZMQ_MESSAGE_BROKER: 'ZMQ_MESSAGE_BROKER',
  MESSAGE_BROKER_PROVIDER:
    env.MESSAGE_BROKER_PROVIDER || 'REDIS_MESSAGE_BROKER',
  REDIS_URL: env.REDIS_URL || 'redis://localhost:6379',
  ZMQ_SERVER_PUSH_URL: env.ZMQ_SERVER_PUSH_URL || 'tcp://localhost:10002',
  ZMQ_SERVER_SUBSCRIBE_URL:
    env.ZMQ_SERVER_SUBSCRIBE_URL || 'tcp://localhost:10001',
};
